# Generated by Django 3.2.20 on 2023-10-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimusic', '0002_historicalsongs_hotsearch_tfidfhotsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsongs',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='歌曲时长'),
        ),
    ]
